### ISSUE TITLE
Typos in imports

### ISSUE THREAD

**Issue by nilekirk** [mvsmal/fable-material-ui#1]
In Fable.Helpers.MaterialUI.fs:
"@material-ui/core/SwipeableDrawerProp" should probably be "@material-ui/core/SwipeableDrawer"
and
"@material-ui/core/TouchRipple" should probably be "@material-ui/core/ButtonBase/TouchRipple"

**Comment by mvsmal** [comment]
@nilekirk Thank you for reporting the issue. I has been fixed.
