### ISSUE TITLE
TabsProps.OnChange doesn't provide the index

### ISSUE THREAD

**Issue by toburger** [mvsmal/fable-material-ui#12]
I didn't manage to get the tabs component to work.

```fsharp
type TabsProp =
	| OnChange of (obj*int->unit)
```

`TabsProp.OnChange` is a callback with a tuple of two arguments, but when handling the callback both arguments are undefined:

```fsharp
TabsProp.OnChange (fun (e, i) ->
	Browser.console.log("e", e)
	Browser.console.log("i", i))
```

But when I call it this way it has the event as argument:

```fhsarp
TabsProp.OnChange (fun e ->
	Browser.console.log("e", e))
```

But then I can't access the index.

**Comment by mvsmal** [comment]
Thank you. I've fixed all events. Now you need to provide `(fun e i -> /* your code */)` and it will work. I've created a new version (1.3.2). Should be available in Nuget shortly.

**Comment by toburger** [comment]
Fantastic! Thank you!
