### ISSUE TITLE
Listitemtext

### ISSUE THREAD

**Issue by yan0lovesha** [mvsmal/fable-material-ui#39]
I am trying to implement following Metarial-UI code in Fable. 
```
          <ListItem
            button
            selected={this.state.selectedIndex === 2}
            onClick={event => this.handleListItemClick(event, 2)}
          >
            **<ListItemText primary="Trash" />**
          </ListItem>
```

The problem is for ListItemText node. I am trying to use below code to translate that line into F#. But the Primary attribute need a ReactNode value. Could you please let me know how to archive it?

`Mui.listItemText [ ListItemTextProp.Primary "How to give a text here" ] []`

**Comment by mvsmal** [comment]
According to the source code of [`Fable.Import.React`](https://github.com/fable-compiler/fable-react/blob/master/src/Fable.React/Fable.Import.React.fs#L53-L60) `ReactNode` is an erased DU.
For example, a string should be passed to `str` helper and then to `ReactChild` and then to `ReactNode` like this:
```fsharp
"Some text" |> str |> ReactChild.Case1 |> ReactNode.Case1
```
or shorter:
```fsharp
"Some text" |> str |> U2.Case1 |> U3.Case1
```

Check https://fable.io/docs/interacting.html#erase-attribute for more info about Erased unions

**Comment by yan0lovesha** [comment]
Oh OK. I should go to check Fable react source. I just tried to search in your repo and found nothing useful to understand ReactNode. Thanks!

**Comment by cmeeren** [comment]
Note that since everything in that chain is erased at runtime, you can also do a simple unbox:

```f#
listItemText [ ListItemTextProp.Primary !!"Some text" ] []
```

**Comment by cmeeren** [comment]
Yes, there is a balance to strike here. As a newcomer, my impression of the Fable/React/MUI combo is that the syntax is rather verbose, much more so than in either the JS samples I've seen (I don't use JS myself) or non-Fable F#.

Case in point:

```jsx
<ListItemText primary="Trash" />
```

becomes

```f#
Mui.listItemText [ ListItemTextProp.Primary ("Trash" |> str |> U2.Case1 |> U3.Case1) ] []
```

In this particular case, I find the unbox acceptable, since `primary` can accept a lot of types, not just strings (e.g. ints, `ReactElement`s, etc.).

But perhaps the ideal solution would be to just define trivial helpers such as

```f#
let elNode (el: ReactElement ) = el |> ReactChild.Case1 |> ReactNode.Case1
let strNode (s: string) = s |> str |> elNode
let intNode (i: int) = s |> ofInt |> elNode
```

This allows to write

```f#
listItemText [ ListItemTextProp.Primary (strNode "Trash") ] []
```
