### ISSUE TITLE
How to merge CSSProperties with CSSProp list?

### ISSUE THREAD

**Issue by yan0lovesha** [mvsmal/fable-material-ui#40]
How to translate the last line of below code to Fable with Material-UI? 

```
const styles = theme => ({
  root: {
    display: 'flex',
  },
  appBar: {
    zIndex: theme.zIndex.drawer + 1,
  },
  drawer: {
    width: drawerWidth,
    flexShrink: 0,
  },
  drawerPaper: {
    width: drawerWidth,
  },
  content: {
    flexGrow: 1,
    padding: theme.spacing.unit * 3,
  },
  **toolbar: theme.mixins.toolbar,**
});
```
I tried to add the toolbar as a Custom style like below:
`Styles.Custom ("toolbar", theme.mixins.toolbar)`

But the types are actually mismatch. It is expecting CSSProp list, but the theme.mixins.toolbar is CSSProperties. 

Is there a way to merge theme.mixins.toolbar with my other styles?

**Comment by mvsmal** [comment]
Try `Styles.Custom'` (with apostrophe). It expects `string * obj` as argument.

**Comment by yan0lovesha** [comment]
It works. Thanks.
