### ISSUE TITLE
How to use SVG icons?

### ISSUE THREAD

**Issue by cmeeren** [mvsmal/fable-material-ui#41]
I am new to Fable and front-end JS stuff (Webpack et al). I have created an [electron boilerplate](https://github.com/cmeeren/fable-elmish-electron-demo) and am currently experimenting with Material-UI. I can't figure out how to make SVG icons work, though. Things like `svgIcon [] [ str "menu" ]` seem to have no effect, and produces an empty element. I have installed the `@material-ui/icons` package. Are there any other requirements for using SVG icons?

**Comment by mvsmal** [comment]
If you want to use `svgIcon` you should do it this way:
https://github.com/mvsmal/fable-material-ui/blob/master/docs/src/Layout/AppBar.fs#L18-L23

Your approach with `str "menu"` will work well with just `icon` component, but don't forget to include icons font. Not sure about Electron, but for html it can be done this way:
```html
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
```

If you want to use `@material-ui/icons` package, you should write you own Fable bindings since it is not a part of this library.
For example smth like this:
```fsharp
open Fable.Core
open Fable.Core.JsInterop
open Fable.Import.React
open Fable.Helpers.React

// ComponentClass
let MenuIcon = importDefault<ComponentClass<IHTMLProp>> "@material-ui/icons/Menu"

// ReactElement
// Probably icons don't need children, so you can pass [] to MenuIcon
// and remove the last argument here
let inline menuIcon props children =
    from MenuIcon (keyValueList CaseRules.LowerFirst props |> unbox) children

// Your view
let view () =
    div [] [
        menuIcon [] []
    ]
```

You can read more about MaterialUI icons here: https://material-ui.com/style/icons/

**Comment by cmeeren** [comment]
Thanks! I was just writing a response here where I arrived at the same conclusion – icon bindings are not part of this library, and that I would have to create them myself.

Is there any significant difference between your suggestion and simply

```f#
let inline menuIcon (props : IHTMLProp list) (elems : ReactElement list) : ReactElement =
  ofImport "Menu" "@material-ui/icons" (keyValueList CaseRules.LowerFirst props) elems
```

or even a general function for all icons:

```f#
let inline icon name (props : IHTMLProp list) (elems : ReactElement list) : ReactElement =
  ofImport name "@material-ui/icons" (keyValueList CaseRules.LowerFirst props) elems
```

Both work, but I have no idea of pros/cons to this approach. The page you linked to (which I read before posting this question without getting much wiser, since I'm a noob at Fable/Elmish/React) mentions something about tree-shaking, not sure if that's relevant here.

**Comment by mvsmal** [comment]
Tree-shaking is relevant here. Tools like webpack or rollup use this technique to make your JS bundle smaller.
When you use a generic function `icon` (btw, I doubt it will work in your example since `@material-ui/icons` is not a component) you pull the whole library. If you import just specific component, your bundling tool will pull only that specific piece of JS code.
This should help: https://material-ui.com/guides/minimizing-bundle-size/#how-to-reduce-the-bundle-size-

I have a generic function for `from ...` in this library, take a look:
https://github.com/mvsmal/fable-material-ui/blob/master/src/Fable.Helpers.MaterialUI.fs#L10-L18

**Comment by cmeeren** [comment]
The generic `icon` function works fine. The documentation mentions that they can be imported that way, but the other way is recommended if the environment doesn't support tree-shaking. See the heading "Imports" in [this section](https://material-ui.com/style/icons/#svg-material-icons).

In any case, thanks! I'll take a look at your code and possibly write a proper bindings library if I can figure out how the props work. Again, this is all new to me.

**Comment by cmeeren** [comment]
Three questions:

1. Would you say that the following is a good way to write bindings for these icons?
2. Would you say it's a good namespace/module?
3. Do I need in any way to care about props mentioned [here](https://material-ui.com/api/svg-icon/) in my bindings, or is that "automatically" handled? I.e., are the bindings below complete, or is some functionality missing?

```f#
module Fable.Helpers.MaterialUI.Icons

open Fable.Core
open Fable.Core.JsInterop
open Fable.Helpers.React.Props

let inline materialEl<'P when 'P :> IHTMLProp>
    (a:Fable.Import.React.ComponentClass<'P>) (b: IHTMLProp list) c : Fable.Import.React.ReactElement =
    Fable.Helpers.React.from a (keyValueList CaseRules.LowerFirst b |> unbox) c

let AccessAlarm = importDefault<Fable.Import.React.ComponentClass<IHTMLProp>> "@material-ui/icons/AccessAlarm"
let inline accessAlarm b c = materialEl AccessAlarm b c

let AccessAlarmOutlined = importDefault<Fable.Import.React.ComponentClass<IHTMLProp>> "@material-ui/icons/AccessAlarmOutlined"
let inline accessAlarmOutlined b c = materialEl AccessAlarmOutlined b c
```

**Comment by mvsmal** [comment]
1. It is a good enough way, the only thing is naming. I would name the first function differently, smth like `materialIcon`. I'm not sure, but I would name the Icons with `Icon` suffix to avoid ambiguity, e.g. `Menu` is a Material UI component too. Btw, `materailEl` function already exists in this library, so you can simply reuse it.
2. Namespace/module looks good to me.
3. The bindings are totally ready to use, nothing more needed. The props mentioned on the page you provided are implemented partially in `fable-react` and in this library. Refer to https://mvsmal.github.io/fable-material-ui/#/api/svg-icon. 
My only sort of concern is children. I didn't have time to check, but it seems, icons never have children, so you can implement them like below:
```fsharp
let MenuIcon = importDefault<Fable.Import.React.ComponentClass<IHTMLProp>> "@material-ui/icons/Menu"
let inline menuIcon b = materialEl MenuIcon b []
```

**Comment by cmeeren** [comment]
I tried your suggested way:

```f#
let AlarmIcon = import<ComponentClass<IHTMLProp>> "AlarmIcon" "@material-ui/icons/Alarm"
let inline alarmIcon b = materialEl AlarmIcon b []
```

However, tree shaking doesn't seem to work. The output is enormous, and compiling takes quite a while, even when using only a single icon.

On the other hand, if I follow [this suggestion](https://github.com/fable-compiler/fable-react/blob/master/docs/using-third-party-react-components.md#member-import) and do

```f#
let inline alarmIcon b : ReactElement = 
  ofImport "AlarmIcon" "@material-ui/icons/Alarm" (keyValueList CaseRules.LowerFirst b) []
```

then tree shaking seems to work properly – the output is significantly smaller, and compilation is much faster.

This leads to two questions:

1. What is the rationale behind having separate definitions for `MenuIcon` and `menuIcon`?
2. Since this library (fable-material-ui) uses the first method, are you sure that tree shaking works properly? (I.e., that the compiled app only contains the MUI components that are actually used?)

**Comment by mvsmal** [comment]
Thank you for this investigation. I've checked again, and indeed, tree-shaking is not working well with my current approach. Stupid me.
I will publish a new version with optimizations soon.

**Comment by cmeeren** [comment]
Happy to have helped! But what was the rationale for the two definitions in the first place? And will I lose anything using single definitions as suggested? (Is that what you will do now?)

Asking purely for my own learning.

**Comment by mvsmal** [comment]
Basically having two definitions would allow you to have both `ComponentClass` and `ReactElement` defined from that component class. In some cases you might need "raw" `ComponentClass`.

**Comment by mvsmal** [comment]
There are some properties of Fable MaterialUI which expect `ReactType`, e.g. `MaterialProp.Component`. And `ReactType` looks like this:
```fsharp
type ReactType =
    U3<string, ComponentClass<obj>, StatelessComponent<obj>>
```

So you can pass a "raw" `ComponentClass` to this erased DU. Smth like this:
```fsharp
MaterialProp.Component (MenuIcon |> U3.Case2)
```

Now I have a problem. If I have a separate import of "raw" `ComponentClass` I lose tree-shaking, and moreover it's a breaking change if I remove it. For example for docs website of this library the difference is 100k on minified bundle with and w/o tree-shaking. Thinking what to do. I will need to ask the small community, which uses this library, to decide.

Thanks a lot to you for raising this topic.

**Comment by cmeeren** [comment]
Thanks for the explanation. You could also ask the Fable maintainers if they know how to support tree shaking and also define `ComponentClass`.

As for the icon bindings I'm creating, I have to support tree shaking anyway because otherwise it's almost unusable (many MB and long compile times), so I'll have to make do without `ComponentClass`.

**Comment by cmeeren** [comment]
For the icon bindings I'm creating, I tried using the namespace/module `Fable.Helpers.MaterialUI.Icons`, but the Fable compiler (which I guess loads all source files in the same context) complained because your library defines `Fable.Helpers.MaterialUI` as a module, and mine as a namespace. If I tried using `module Fable.Helpers.MaterialUI` and then `Icons` as a sub-module, I got a similar error (two files defining the same module, namely `Fable.Helpers.MaterialUI`). Do you know of any way I can use `Fable.Helpers.MaterialUI.` prefix? (Right now I have just opted for `Fable.Helpers.MaterialUIIcons` to get around it.)

**Comment by cmeeren** [comment]
Based on https://github.com/fable-compiler/Fable/issues/1656 the only way I can use `Fable.Helpers.MaterialUI` is if it's defined as a namespace, and not a module. So it seems there's no way I can currently use it. I'll have to use `Fable.Helpers.MaterialUIIcons` or something like that.

**Comment by mvsmal** [comment]
@cmeeren Since I'm going to release a breaking change (remove raw ComponentClasses), I can move the library to a different module, such as `Fable.Helpers.MaterialUI.Core` and `Fable.Helpers.MaterialUI` will become the main namespace for all related libraries (`Styles` is gonna be a separate one soon https://material-ui.com/css-in-js/basics/#installation).

Then I'll be able to move `Fable.MaterialUI.Props` to `Fable.Helpers.MaterialUI.Props` as I wanted initially.

A question to you: do you have a dependency on Fable.MaterialUI in your nuget package or is it completely standalone? If you have, you could set the minimum version to 3.x

**Comment by cmeeren** [comment]
Thanks! I haven't released yet, but when I do it will be completely standalone.

As for namespace/module naming conventions, see https://github.com/fable-compiler/Fable/issues/1656#issuecomment-443495401. Perhaps just `namespace MaterialUI` works just as well as `namespace Fable.Helpers.MaterialUI`? Your call, just wanted to let you know of the comment.

**Comment by mvsmal** [comment]
I would go for `Fable.MaterialUI` to keep the connection to Fable and avoid confusion for non-Fable projects. In this case your library will be applicable even with the current state of `Fable.MaterialUI`.

When are you going to release it approximately? Are you preparing any docs? I'd put a link to them in my docs.

**Comment by cmeeren** [comment]
Agreed, sounds good to me. So if I understand correctly, you'll do `module Fable.MaterialUI.Core`, and I'll do `module Fable.MaterialUI.Icons`, right?

**Comment by mvsmal** [comment]
Yes, you understood correctly. I'll then add a link to the readme. Thanks!

**Comment by cmeeren** [comment]
Done: https://github.com/cmeeren/Fable.MaterialUI.Icons

v1.0.0 first release is in the pipeline and will be deployed to Nuget shortly. Note that it can't be used with Fable.MaterialUI v2.x.x, it requires the new version you are working on.

I will also create similar bindings for [mdi-material-ui](https://github.com/TeamWertarbyte/mdi-material-ui) (which is [linked to](https://material-ui.com/style/icons/) from the official Material-UI docs). Will let you know when it's done so you can link to that, too.

**Comment by cmeeren** [comment]
Here's the other one: https://github.com/cmeeren/Fable.MaterialUI.MaterialDesignIcons

**Comment by cmeeren** [comment]
Do you know when v3 will be released (#43) with the new namespace/module names? I can't use my icon bindings until v3 due to the namespace clashes.

**Comment by mvsmal** [comment]
@cmeeren Sorry, I didn't have time to work on it. Today I've published version 2.5.0 with `Fable.MaterialUI` namespace for `Props`, `Themes` and `Colors`. It is not a breaking change, actually, but now you can use your package without namespace clashes.

**Comment by cmeeren** [comment]
Oh sorry, perhaps we have misunderstood each other. I have released the icons with `module Fable.Helpers.MaterialUI.Icons`, which still clashes since in my package `Fable.Helpers.MaterialUI` is a namespace whereas in your package it's a module.

How do you propose we should solve this? I doubt I have many users yet, so I can release 2.0.0 with the component helpers in another namespace, but I think we should aim for compatibility and consistency with Fable.MaterialUI v3. What is your plan there?

Let me know if I am being unclear.

**Comment by mvsmal** [comment]
In your code I see `Fable.MaterialUI` as a namespace:
https://github.com/cmeeren/Fable.MaterialUI.Icons/blob/master/src/Fable.MaterialUI.Icons/Icons.fs#L6

In my code I have it the same since version 2.5.0:
https://github.com/mvsmal/fable-material-ui/blob/master/src/Fable.Helpers.MaterialUI.Props.fs#L1

You don't use `Fable.Helpers.MaterialUI` namespace, do you? I haven't found it. 
There shouldn't be any clash.

**Comment by cmeeren** [comment]
Terribly sorry, I had some bad cached packages from local testing, so things got mixed up locally. Works correctly. Thanks!
