### ISSUE TITLE
How to get properties of an event parameter?

### ISSUE THREAD

**Issue by yan0lovesha** [mvsmal/fable-material-ui#42]
This maybe a question not only to Fable-Material-UI, also about how to use Fable. I hope I can get some help from you. :)

For some event in MaterialUI, a lot of parameters are defined as obj type.
OnBackdropClick of (obj->unit)

In js, I can just use obj.Property to get the property value.
In FS, it will be an error. Is there a way to get property value based on the obj parameter type?

**Comment by mvsmal** [comment]
Fable provides dynamic typing for simpler interaction with JavaScript
```fsharp
open Fable.Core.JsInterop

let stringProp : string = !!obj?stringProp
```

`?` operator allows to access a property dynamically
`!!` is an alias for `unbox`, without it your property is `obj`

Refer to: https://fable.io/docs/interacting.html#dynamic-typing

**Comment by yan0lovesha** [comment]
Thank you!
