### ISSUE TITLE
Wrong custom values ?

### ISSUE THREAD

**Issue by MangelMaxime** [mvsmal/fable-material-ui#44]
[Here](https://github.com/mvsmal/fable-material-ui/blob/master/src/Fable.Helpers.MaterialUI.Props.fs#L485-L522) the custom value generate string with \`` in it.

Ex:

```fs
let inline ``Align-content-xs-center`` props = Custom ("align-content-xs-center``", props)
```

Is it normal or should it be like:

```fs
let inline ``Align-content-xs-center`` props = Custom ("align-content-xs-center", props)
```

*I didn't test the code. I was just exploring the code by curiosity^^ so perhaps its working I have no idea*

**Comment by mvsmal** [comment]
@MangelMaxime Thanks a lot for the code review. I've published version [2.4.2](https://github.com/mvsmal/fable-material-ui/releases/tag/2.4.2) with the fix.
