### ISSUE TITLE
How to use ListItemTextProp.Primary (or in general, ReactNode)?

### ISSUE THREAD

**Issue by cmeeren** [mvsmal/fable-material-ui#46]
When trying to use `ListItemTextProp.Primary`, I have a problem. The DU case takes a `ReactNode`, but I have no idea how to instantiate it. The following works, but I guess it's not the "correct" way since I'm doing unsafe unboxing:

```f#
ListItemTextProp.Primary (unbox <| str "My text")
// or
ListItemTextProp.Primary (unbox "My text")
```

How to I use this property, as well as others accepting `ReactNode`s?

**Comment by mvsmal** [comment]
Duplication of #39 

@cmeeren, Please, find the answer here: https://github.com/mvsmal/fable-material-ui/issues/39#issuecomment-439856771
