### ISSUE TITLE
F# List module unusable when Fable.Helpers.MaterialUI is opened

### ISSUE THREAD

**Issue by cmeeren** [mvsmal/fable-material-ui#47]
It seems that when I have `open Fable.Helpers.MaterialUI`, I cannot use the `FSharp.Collections.List` module (except if I fully prefix it every time). I can't even `open FSharp.Collections.List` after `open Fable.Helpers.MaterialUI` or do `module List = FSharp.Collections.List`, because `List` will still resolve to `Fable.Helpers.MaterialUI.List`. Is this behavior/naming intentional on your part?

![image](https://user-images.githubusercontent.com/7766733/50379329-c0498880-0647-11e9-9ef6-fbabde6cb306.png)

**Comment by mvsmal** [comment]
Yes, unfortunately I used this name for importing the `List` MaterialUI component. In version 3 this issue will be solved by removing the imports. For now you can workaround it with
```fsharp
module Mui = Fable.Helpers.MaterialUI

Mui.list [] []
```

**Comment by cmeeren** [comment]
Thanks. Unfortunately, if I do that, I have to use the `Mui` prefix for all helpers, which I'd rather avoid. Looking forward to v3! Do you know when it might be released?

**Comment by mvsmal** [comment]
I will only have time next week. I also need to catch up with MaterialUI 3.7.0

**Comment by mvsmal** [comment]
Fixed in version 3.
