### ISSUE TITLE
Homepage "Get started" button link is wrong

### ISSUE THREAD

**Issue by cmeeren** [mvsmal/fable-material-ui#48]
![image](https://user-images.githubusercontent.com/7766733/50458814-44608080-0966-11e9-9256-ddd538ec44ad.png)

The button leads to 

`https://mvsmal.github.io/#/getting-started/installation`

but should lead to 

`https://mvsmal.github.io/fable-material-ui/#/getting-started/installation`

**Comment by mvsmal** [comment]
Fixed with [de0b6bd](https://github.com/mvsmal/fable-material-ui/commit/de0b6bd532bbda0ba8daece94b0a8b40c6d645b1) commit
