### ISSUE TITLE
Improve prop discoverability

### ISSUE THREAD

**Issue by cmeeren** [mvsmal/fable-material-ui#49]
When using this library (and to some extent the React bindings in general), I am often finding it rather inconvenient to figure out where my desired property DU case is.

Let's take a recent example I came across, the `<ListItem selected />` property. I tried writing `Selected`, but Intellisense only offered `PaletteActionProp.Selected`, which I expect is defined last in `Fable.MaterialUI.Props` and thus shadows all other `Selected` cases.

Out of luck for the easy way out, I then have to basically know by heart all the prop types that could be used here, because that's neither easily discoverable in the IDE nor particularly strongly typed (AFAIK many prop types are `IHTMLProp`, so I can inadvertently use the wrong one).

For example, I have used `fable-material-UI` enough to know that many components have their own props, so I try `ListItemProp`, but it contains no `Selected`.

Okay, where to next? I have also seen a presumably more general `MaterialProp`, but that doesn't contain any `Selected` case either.

Still no luck. What's the next more general prop type? In any case, I'm getting tired of trying to figure out prop type names to qualify. Should I go to this repo and search for "Selected" and see what crops up? That wouldn't actually lead anywhere in this particular case, because it turned out that what I'm looking for is `HTMLAttr.Selected`. In other cases, I might have to go another step to `DOMAttr` to find my desired property.

With the above rant in mind: Can you think of any way to improve discoverability of prop types? I can't easily see how this can be done, since there are bound to be many name collisions. But it's here I experience the most friction while using this API, so I thought I'd post an issue anyway.

**Comment by cmeeren** [comment]
Hm, I just discovered that the fable-material-ui API documentation describes all these types (case in point, `HTMLAttr.Selected` for [ListItem](https://mvsmal.github.io/fable-material-ui/#/api/list-item). My bad for not RTFM 😅 

I'd argue that my rant still has some merit though, since it's inconvenient to look up the API documentation for components each time I know the property name, but not the type it's in.

**Comment by mvsmal** [comment]
I've been thinking about it a lot. On one hand I could create all properties under the corresponding "`ElementProp`" type. It would make the discoverability higher, but also increases the code duplication. Also I wanted to put everything into one type, like `HTMLProp`, but then I realized it's not possible, because `ButtonProp.Variant` has a different type than `TextField.Variant` and many other similar examples. So I've chosen the middle here, some props have a separate type, and others are combined into `MaterialProp` or `ChildrenProp`, as well as reuse of `HTMLProp` and `DOMAttr`

**Comment by cmeeren** [comment]
Given the options, I think you've chosen a fair middle ground. I can't think of any better options at the moment. [Fabulous](https://fsprojects.github.io/Fabulous/index.html#getting=started) has chosen another syntax entirely based on optional arguments, but that would be a clear deviation from Fable/React and not something to do in a single library such as `fable-material-ui`.

Feel free to close.
