### ISSUE TITLE
Make helpers accept seq<IHTMLProp> instead of list

### ISSUE THREAD

**Issue by cmeeren** [mvsmal/fable-material-ui#51]
React helpers generally seem to accept `seq<IHTMLProp>`, whereas in fable-material-ui, helpers seem to take `IHTMLProp list`. This creates some friction at times. I suggest changing them to accept `seq<IHTMLProp>`. I'm unsure if you need to use `#seq<IHTMLProp>` or if it's enough with `seq<IHTMLProp>`.

**Comment by mvsmal** [comment]
Fixed in [3.1.0](https://github.com/mvsmal/fable-material-ui/releases/tag/3.1.0)
