### ISSUE TITLE
How to create a ExpansionPanelSummaryProp.ExpandIcon

### ISSUE THREAD

**Issue by halcwb** [mvsmal/fable-material-ui#54]
I want to create an expansion panel with an 'expand more icon'. The documentation just says that I should use `ExpansionPanelSummaryProp.ExpandIcon` to create the attribute for the icon. However it needs a ReactNode to create the icon. How do I do this?

**Comment by mvsmal** [comment]
Hello @halcwb, please have a look at my comment: https://github.com/mvsmal/fable-material-ui/issues/39#issuecomment-439856771 and the other replies on that issue.

**Comment by halcwb** [comment]
Thanks, got it.
