### ISSUE TITLE
Update to Fable.Core 3 and Fable.React 5

### ISSUE THREAD

**Issue by cmeeren** [mvsmal/fable-material-ui#56]
New versions have been released, see the [this Fable blog post](https://fable.io/blog/Announcing-2-2.html#other-packages-fulma-thoth-json-fable-simplehttp-). There are some breaking changes.

I'll create a PR.

**Comment by cmeeren** [comment]
Note that this is blocked by https://github.com/elmish/react/issues/41. Will likely be fixed this week.

**Comment by cmeeren** [comment]
Related questions, I asked them in the Fable.React repo since it's related to the breaking Fable changes: https://github.com/fable-compiler/fable-react/issues/151

**Comment by cmeeren** [comment]
Based on the discussion in fable-compiler/fable-react#151 I think I've managed to convert most, but I'm unsure of the following:

* `type RefProp = U2<obj,(Fable.React.ReactInstance->unit)>`
  * Used in `MaterialProp.InputRef`, `ButtonBaseProp.ButtonRef`, and `RootRefProp.RootRef`
* `MaterialProp.AnchorEl of Fable.React.ReactInstance`
* `MaterialProp.Container of  of Fable.React.ReactInstance`

Also, I'm in general wondering if all refs should be just callbacks, not `obj`, since Fable.React seems to provide no way to call `React.createRef` if my understanding in https://github.com/fable-compiler/fable-react/issues/154 is correct.

**Comment by mvsmal** [comment]
Version 4.0.0 has been release with new Fable dependencies
