### ISSUE TITLE
Add missing paket exe

### ISSUE THREAD

**Issue by cmeeren** [mvsmal/fable-material-ui#57]
`fake build` fails because the `.paket` directory doesn't contain `paket.exe`. Should there be a paket magic mode boostrapper here?

**Comment by mvsmal** [comment]
Hi @cmeeren, I should have mentioned that in docs. I switched to paket as dotnet global tool. I will have time only in 2 weeks to work on the updates.

**Comment by mvsmal** [comment]
I have updated Readme with info about `paket` as a global tool
