### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by 64J0** [mvsmal/fable-material-ui#98]
I want to make a contribution to the docs but I'm not sure if it will be useful since the last update here is from two years ago. Btw, this is the page I would submit the changes: https://mvsmal.github.io/fable-material-ui/#/api/circular-progress.

**Comment by halcwb** [comment]
I think this project has been abandoned. There is a very good alternative: [Feliz.MaterialUI](https://zaid-ajaj.github.io/Feliz/#/UIFrameworks/Mui).
